    -- master horse training
    ['masterhorsebrush'] = {['name'] = 'masterhorsebrush', ['label'] = 'Master Brush',  ['weight'] = 300, ['type'] = 'item', ['image'] = 'masterhorsebrush.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'brush used by a horse trainer'},
    ['mastercarrot']     = {['name'] = 'mastercarrot',     ['label'] = 'Master Carrot', ['weight'] = 100, ['type'] = 'item', ['image'] = 'mastercarrot.png',     ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'carrot used by a horse trainer'},

    -- horse xp tokens
    ['horsexp5']    = {['name'] = 'horsexp5',    ['label'] = '5 Horse XP',    ['weight'] = 0, ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp10']   = {['name'] = 'horsexp10',   ['label'] = '10 Horse XP',   ['weight'] = 0, ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp25']   = {['name'] = 'horsexp25',   ['label'] = '25 Horse XP',   ['weight'] = 0, ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp50']   = {['name'] = 'horsexp50',   ['label'] = '50 Horse XP',   ['weight'] = 0, ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp100']  = {['name'] = 'horsexp100',  ['label'] = '100 Horse XP',  ['weight'] = 0, ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp250']  = {['name'] = 'horsexp250',  ['label'] = '250 Horse XP',  ['weight'] = 0, ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp500']  = {['name'] = 'horsexp500',  ['label'] = '500 Horse XP',  ['weight'] = 0, ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp1000'] = {['name'] = 'horsexp1000', ['label'] = '1000 Horse XP', ['weight'] = 0, ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
